/**
 * Coolify API command types
 */

export interface CoolifyCommand {
  /** API endpoint path (e.g., /databases/postgresql) */
  endpoint: string;
  /** HTTP method */
  method: 'POST' | 'GET' | 'PUT' | 'DELETE';
  /** Request payload */
  payload: Record<string, unknown>;
  /** Comment describing the resource */
  comment?: string;
  /** Resource name for display */
  name: string;
}

export interface CoolifyDatabaseCommand extends CoolifyCommand {
  endpoint: `/databases/${CoolifyDatabaseType}`;
  resourceType: 'database';
  databaseType: CoolifyDatabaseType;
}

export type CoolifyDatabaseType =
  | 'postgresql'
  | 'mysql'
  | 'mariadb'
  | 'mongodb'
  | 'redis'
  | 'keydb'
  | 'dragonfly'
  | 'clickhouse';

export interface CoolifyServiceCommand extends CoolifyCommand {
  endpoint: '/services';
  resourceType: 'service';
  serviceType: CoolifyServiceType;
}

export type CoolifyServiceType =
  | 'minio'
  | 'rabbitmq'
  | 'keycloak'
  | 'seq'
  | 'mailpit'
  | 'kafka'
  | 'elasticsearch'
  | 'custom';

export interface CoolifyApplicationCommand extends CoolifyCommand {
  endpoint: '/applications/dockerimage' | '/applications/dockerfile';
  resourceType: 'application';
  buildPack: CoolifyBuildPack;
}

export interface CoolifyProjectCommand extends CoolifyCommand {
  endpoint: '/projects';
  resourceType: 'project';
}

export type CoolifyBuildPack =
  | 'nixpacks'
  | 'dockerfile'
  | 'docker-compose'
  | 'static'
  | 'dockerimage';

export interface CoolifyOutput {
  commands: CoolifyCommand[];
  script: string;
}

/**
 * Format a single command as a curl request
 * Handles shell variable expansion for $PROJECT_UUID
 */
export function formatCommand(cmd: CoolifyCommand): string {
  // Check if payload contains shell variables that need expansion
  const hasShellVars = JSON.stringify(cmd.payload).includes('$PROJECT_UUID');

  if (hasShellVars) {
    // Use double quotes and escape internal quotes for shell variable expansion
    const payloadJson = JSON.stringify(cmd.payload, null, 2)
      .split('\n')
      .map((line, i) => (i === 0 ? line : '  ' + line))
      .join('\n')
      .replace(/"/g, '\\"')
      .replace(/\$PROJECT_UUID/g, '${PROJECT_UUID}');

    return `curl -X ${cmd.method} "\${COOLIFY_API_URL}/api/v1${cmd.endpoint}" \\
  -H "Authorization: Bearer \${COOLIFY_TOKEN}" \\
  -H "Content-Type: application/json" \\
  -d "${payloadJson}"`;
  }

  const payloadJson = JSON.stringify(cmd.payload, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : '  ' + line))
    .join('\n');

  return `curl -X ${cmd.method} "\${COOLIFY_API_URL}/api/v1${cmd.endpoint}" \\
  -H "Authorization: Bearer \${COOLIFY_TOKEN}" \\
  -H "Content-Type: application/json" \\
  -d '${payloadJson}'`;
}

/**
 * Format a project creation command that captures the UUID
 */
function formatProjectCommand(cmd: CoolifyCommand): string {
  const payloadJson = JSON.stringify(cmd.payload, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : '  ' + line))
    .join('\n');

  return `PROJECT_RESPONSE=$(curl -s -X ${cmd.method} "\${COOLIFY_API_URL}/api/v1${cmd.endpoint}" \\
  -H "Authorization: Bearer \${COOLIFY_TOKEN}" \\
  -H "Content-Type: application/json" \\
  -d '${payloadJson}')

# Extract project UUID from response
PROJECT_UUID=$(echo "$PROJECT_RESPONSE" | grep -o '"uuid":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$PROJECT_UUID" ]; then
  echo "Error: Failed to create project. Response: $PROJECT_RESPONSE"
  exit 1
fi

echo "  Created project with UUID: $PROJECT_UUID"`;
}

/**
 * Format all commands as a bash script with curl requests
 */
export function formatOutput(output: CoolifyOutput): string {
  // Check if there's a project command
  const projectCmd = output.commands.find((cmd) => cmd.endpoint === '/projects');
  const otherCommands = output.commands.filter((cmd) => cmd.endpoint !== '/projects');

  const lines: string[] = [
    '#!/bin/bash',
    '# Generated by aspire2coolify',
    '# Coolify API deployment script',
    '#',
    '# Required environment variables:',
    '#   COOLIFY_API_URL - Your Coolify instance URL (e.g., https://coolify.example.com)',
    '#   COOLIFY_TOKEN   - Your Coolify API token',
    '#',
    '# Usage:',
    '#   export COOLIFY_API_URL=https://coolify.example.com',
    '#   export COOLIFY_TOKEN=your-api-token',
    '#   ./deploy.sh',
    '',
    'set -e',
    '',
    '# Validate environment variables',
    'if [ -z "$COOLIFY_API_URL" ]; then',
    '  echo "Error: COOLIFY_API_URL environment variable is not set"',
    '  exit 1',
    'fi',
    '',
    'if [ -z "$COOLIFY_TOKEN" ]; then',
    '  echo "Error: COOLIFY_TOKEN environment variable is not set"',
    '  exit 1',
    'fi',
    '',
    'echo "Deploying to Coolify at $COOLIFY_API_URL"',
    'echo ""',
    '',
  ];

  // Add project creation if needed
  if (projectCmd) {
    if (projectCmd.comment) {
      lines.push(`# ${projectCmd.comment}`);
    }
    lines.push(`echo "Creating project: ${projectCmd.name}..."`);
    lines.push(formatProjectCommand(projectCmd));
    lines.push('echo ""');
    lines.push('');
  }

  for (const cmd of otherCommands) {
    if (cmd.comment) {
      lines.push(`# ${cmd.comment}`);
    }
    lines.push(`echo "Creating ${cmd.name}..."`);
    lines.push(formatCommand(cmd));
    lines.push('echo ""');
    lines.push('');
  }

  lines.push('echo "Deployment complete!"');

  return lines.join('\n');
}
